name: network_font
description: network_font will help you use your custom font from network, so you don't have to store those fonts in your project directory's asset folder.
version: 0.0.5
homepage: https://github.com/kithe-raker/network_font

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Get user's local path
  path_provider: ^2.0.1

  # Make get request to network font
  http: ^1.1.0

  # Store data to user's local
  hive: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
